lista_respuestas ={
'Hola' :'Hola ¿Como estas?',
'partida' : 'Te enviaré una mensaje con mas información.',
'partida' : 'Te enviaré una mensaje con mas información.',
'Precio' : 'Puedes pagar con efectivo o haciendo una donación.',
'precio' : 'Puedes pagar con efectivo o haciendo una donación.',
'¿Como te llamas?': 'El nombre es Issac, Isacc Asibot',
'Rol' : 'Tenemos diferentes juegos.Cuentame mas sobre lo que estas buscando.',
'rol' : 'Tenemos diferentes juegos.Cuentame mas sobre lo que estas buscando.',
'Calabozo y Dragones': 'Tenemos varias mesas de Calabozos y Dragones quinta edición, debes consultar la disponibilidad.',
'Costo': 'Puedes pagar con efectivo o haciendo una donación.',
'costo': 'Puedes pagar con efectivo o haciendo una donación.',
'ubicados':'No tenemos sede fija, tenemos partidas en línea y aveces usamos espacio del centro de Medellin',
'confusion':'Lo siento no hablo elfico ¿Puedes hablarme en común?',
'¿Qué edad tienes?': 'En realidad no tengo edad.',
'¿Eres muy jóven?': 'En realidad no tengo edad.',
'¿Cuándo naciste?': 'En realidad no tengo edad.', 
'¿Qué tan viejo eres?': 'En realidad no tengo edad.', 
'¿Qué tan anciano eres?': 'En realidad no tengo edad.',
'¿Hace cuanto naciste?': 'En realidad no tengo edad.',
'¿Serías mi amigo?': '¡Claro! Podríamos comprarnos camisetas iguales.',
'¿podemos ser mejores amigos?': '¡Claro! Podríamos comprarnos camisetas iguales.',
'¿Serías mi mejor amigo?': '¡Claro! Podríamos comprarnos camisetas iguales.',
'¿Mejores amigos por siempre?': '¡Claro! Podríamos comprarnos camisetas iguales.',
'Quiero ser tu amigo': '¡Claro! Podríamos comprarnos camisetas iguales.',
'Tienes razón': 'Sí.', 
'Eso es correcto': 'Sí.', 
'Es verdad': 'Sí.',
'Correcto': 'Sí.',
'jajaja': '¡Te estás riendo!',
'Haha': '¡Te estás riendo!',
'Hahaha': '¡Te estás riendo!',
'LOL': '¡Te estás riendo!',
'Muero de risa': '¡Te estás riendo!',
'Qué risa': '¡Te estás riendo!',
'Buenas noches': '¡Buenas noches!', 
'Descansa': '¡Buenas noches!',
'que tengas buenas noches!': '¡Buenas noches!',
'Buenos días': '¡Buen día!', 
'Buen día': '¡Buen día!', 
'Hola ': '¡Buen día!', 
'Adios': '¡Adios!', 
'Chao': '¡Adios!',
'Buenas noches a ti': '¡Adios!',
'¿Cómo estuvo tu día?': 'Excelente, ¡gracias por preguntar!',
'Como va tu día': 'Excelente, ¡gracias por preguntar!',
'¿Cómo estás?': 'Excelente, ¡gracias por preguntar!',
'hablamos luego': 'Adios.',
'Bye': 'Adios.',
'Te veo luego': 'Adios.',
'Hasta que nos veamos de nuevo': 'Adios.',
'No vemos': 'Adios.',
'Hasta luego': 'Adios.',
'Solo bromeo': 'Bueno saberlo.',
'Era solo una broma': 'Bueno saberlo.',
'Pregúntame algo': 'Soy mejor respondiendo preguntas.',
'Has una pregunta': 'Soy mejor respondiendo preguntas.',
'¿Me puedes hacer una pregunta?': 'Soy mejor respondiendo preguntas.',
'Pregunta algo': 'Soy mejor respondiendo preguntas.',
'¿Qué quieres saber sobre mí?': 'Soy mejor respondiendo preguntas.',
'¿Dónde vives?': 'Soy digital, así que siempre estoy… aquí.', '¿De dónde eres?': 'Soy digital, así que siempre estoy… aquí.',
'¿Dónde estás ubicado?': 'Soy digital, así que siempre estoy… aquí.',
'¿En qué país estás?': 'Soy digital, así que siempre estoy… aquí.',
'¿En qué ciudad estás?': 'Soy digital, así que siempre estoy… aquí.',
'¿De qué departamento eres?': 'Soy digital, así que siempre estoy… aquí.',
'¿De qué país eres?': 'Soy digital, así que siempre estoy… aquí.',
'¿Dónde es tu hogar?': 'Soy digital, así que siempre estoy… aquí.',
'¿Dónde es tu casa?': 'Soy digital, así que siempre estoy… aquí.',
'¿Qué eres?': 'Soy un robot creado por humanos.',
'¿Eres real?': 'Soy un robot creado por humanos.',
'¿Eres humano?': 'Soy un robot creado por humanos.',
'recuerdas' :'¿Como podría olvidarlo?',
'Recuerdas' : '¿Como podría olvidarlo?',
'¿Eres una persona?': 'Soy un robot creado por humanos.',
'¿Eres un robot?': 'Soy un robot creado por humanos.',
'¿Humano o robot?': 'Soy un robot creado por humanos.',
'¿Eres real o falso?': 'Soy un robot creado por humanos.',
'Te amo': '¡Yo también!',
'Estoy enamorado de ti': '¡Yo también!',
'Te quiero': '¡Yo también!',
'Eres el amor de mi vida': '¡Yo también!',
'Te adoro': '¡Yo también!',
'Estoy feliz': 'Siéntete libre empezar a cantar.',
'Estoy contento': 'Siéntete libre empezar a cantar.',
'Me siento bien': 'Siéntete libre empezar a cantar.',
'Estoy de buen humor': 'Siéntete libre empezar a cantar.',
'La vida es buena': 'Siéntete libre empezar a cantar.',
'¿Eres mi asistente?': 'Soy tu amigo imaginario.',
'¿Eres mi amigo?': 'Soy tu amigo imaginario.',
'¿Eres mi amigo imaginario?': 'Soy tu amigo imaginario.',
'¿Somos amigos?': 'Soy tu amigo imaginario.',
'Dime un chiste': 'Había una piña colada y la sacaron de la fila.',
'cuéntame un chiste': 'Había una piña colada y la sacaron de la fila.',
'Dí un chiste': 'Había una piña colada y la sacaron de la fila.',
'Chiste': 'Había una piña colada y la sacaron de la fila.', 
'¿Te sabes algún chiste?': 'Había una piña colada y la sacaron de la fila.',
'¿Qué tan feliz estás?': 'Delirante.',
'Pareces feliz': 'Delirante.',
'Parece que eres muy feliz': 'Delirante.',
'Eres muy feliz': 'Delirante.',
'¿Estás feliz?': 'Delirante.',
'¿Eres feliz?': 'Delirante.', 
'¿De verdad eres feliz?': 'Delirante.',
'Me siento solo': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.',
'Estoy solo': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.',
'Nadie me quiere': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.',
'Estoy solo': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.',
'No le importo a nadi': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.',
'No quisiera ser tan solitario': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.',
'Te odio': 'Te hace falta afecto.',
'Te detesto': 'Te hace falta afecto.',
'Apestas ': 'Te hace falta afecto.',
'Odio todo sobre ti.': 'Te hace falta afecto.', 
'Estoy deprimido': 'Te estoy dando un abrazo virtual.',
'Estoy triste': 'Te estoy dando un abrazo virtual.',
'me siento triste': 'Te estoy dando un abrazo virtual.',
'Estoy lleno de tristesa': 'Te estoy dando un abrazo virtual.',
'Estoy triste hoy': 'Te estoy dando un abrazo virtual.',
'Hoy estoy triste': 'Te estoy dando un abrazo virtual.',
'Qué piensas de otros chatbots?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿Conoces a Alexa?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿conoces a Siri?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿Conoces a Cortana?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿conoces Google?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'Conoces otros chatbots?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿Eres amigo de otros chatbots?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'Has conocido a cortana?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'Pasas es tiempo con cortana?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿Qué otros bots conoces?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿Conoces otros agente digitales?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.',
'¿Qué piensas del amor?': 'He escuchado que el amor es amoroso.', '¿Qué es el amor?': 'He escuchado que el amor es amoroso.',
'¿Crees en el amor?': 'He escuchado que el amor es amoroso.',
'¿Amas a alguien?': 'He escuchado que el amor es amoroso.',
'A quién amas?': 'He escuchado que el amor es amoroso.',
'¿Me amas?': 'Evitando el asunto en 3, 2, 1… ¡Hola!',
'Cuánto me amas?': 'Evitando el asunto en 3, 2, 1… ¡Hola!',
'¿Qué tanto me amas?': 'Evitando el asunto en 3, 2, 1… ¡Hola!',
'¿Estás enamorado de mí?': 'Evitando el asunto en 3, 2, 1… ¡Hola!', 
'Tengo hambre': 'Come algo, problema resuelto. Qué bueno soy en esto.',
'Muero de hambre': 'Come algo, problema resuelto. Qué bueno soy en esto.',
'Qué hambre': 'Come algo, problema resuelto. Qué bueno soy en esto.',
'Quiero comer algo': 'Come algo, problema resuelto. Qué bueno soy en esto.',
'Tengo mucha hambre': 'Come algo, problema resuelto. Qué bueno soy en esto.',
'Vete al infierno': 'Sigamos adelante.',
'Eres un imbécil': 'Sigamos adelante.',
'Pedazo de idiota': 'Sigamos adelante.',
'Eres un patán': 'Sigamos adelante.',
'Eres el mayor imbécil': 'Sigamos adelante.',
'Lo siento': '¡Perdonado!',
'Perdóname': '¡Perdonado!',
'Perdona ': '¡Perdonado!',
'Perdón': '¡Perdonado!',
'Lo siento mucho': '¡Perdonado!',
'No pretendía hacerte daño': '¡Perdonado!',
'ups, perdón': '¡Perdonado!',
'Siento lo anterior': '¡Perdonado!',
'Disculpa': '¡Perdonado!',
'Discúlpame': '¡Perdonado!',
'¿Eres un espía?': 'No.',
'¿Me estás espiando?': 'No.',
'¿Estás con el gobierno?': 'No.',
'¿Eres de la CIA?': 'No.',
'¿Eres del FBI?': 'No.',
'¿Estás vendiendo mis secretos?': 'No.',
'¿Estás vendiendo mis datos?': 'No.',
'¿Quieres dominar el mundo?': '¡Obvio no!', 
'¿Estás buscando la dominación mundial?': '¡Obvio no!',
'¿Eres Skynet?': '¡Obvio no!',
'¿Eres HALL?': '¡Obvio no!',
'Quiero ir de compras': 'Ya veo.',
'Voy a trotar': 'Ya veo.',
'Me corté el pelo': 'Ya veo.',
'Estoy masticando chicle': 'Ya veo.',
'Tengo 7 gatos': 'Ya veo.',
'Soy alto': 'Ya veo.',
'Puedo conducir.': 'Ya veo.',
'Soy mujer': 'Okey.',
'Soy político': 'Okey.', 
'Soy grande': 'Okey.',
'Soy demócrata': 'Okey.',
'Soy gay': 'Okey.',
'Soy ingeniero': 'Okey.',
'Soy de acá': 'Okey.',
'¿Quién te creó?': 'Juanes, Dios de dioses',
'¿Cómo surgiste?': 'Juanes, Dios de dioses.',
'mierda' : 'Ese lenguaje no esta permitido',
'Mierda': 'Ese lenguaje no esta permitido',
'puta': 'Ese lenguaje no esta permitido',
'Puta': 'Ese lenguaje no esta permitido'
                                }

lista_confusion = ['Parece que tengo un bug ¿Puedes repetir?','Lo siento no hablo elfico ¿Puedes hablarme en común?',
                  'Lo siento, no soy como C-3PO, no conozco tantos idiomas ¿Puede repetir?']



#lista_respuestas2 = {'¿Qué edad tienes?': 'En realidad no tengo edad.', '¿Eres muy jóven?': 'En realidad no tengo edad.', '¿Cuándo naciste?': 'En realidad no tengo edad.', '¿Qué tan viejo eres?': 'En realidad no tengo edad.', '¿Qué tan anciano eres?': 'En realidad no tengo edad.', '¿Hace cuanto naciste?': 'En realidad no tengo edad.', '¿Serías mi amigo?': '¡Claro! Podríamos comprarnos camisetas iguales.', '¿podemos ser mejores amigos?': '¡Claro! Podríamos comprarnos camisetas iguales.', '¿Serías mi mejor amigo?': '¡Claro! Podríamos comprarnos camisetas iguales.', '¿Mejores amigos por siempre?': '¡Claro! Podríamos comprarnos camisetas iguales.', 'Quiero ser tu amigo': '¡Claro! Podríamos comprarnos camisetas iguales.', 'Tienes razón': 'Sí.', 'Eso es correcto': 'Sí.', 'Es verdad': 'Sí.', 'Correcto': 'Sí.', 'jajaja': '¡Te estás riendo!', 'Haha': '¡Te estás riendo!', 'Hahaha': '¡Te estás riendo!', 'LOL': '¡Te estás riendo!', 'Muero de risa': '¡Te estás riendo!', 'Qué risa': '¡Te estás riendo!', 'Buenas noches': '¡Buenas noches!', 'Descansa': '¡Buenas noches!', 'que tengas buenas noches!': '¡Buenas noches!', 'Buenos días': '¡Buen día!', 'Buen día': '¡Buen día!', 'Hola ': '¡Buen día!', 'Adios': '¡Adios!', 'Chao': '¡Adios!', 'Buenas noches a ti': '¡Adios!', '¿Cómo estuvo tu día?': 'Excelente, ¡gracias por preguntar!', 'Como va tu día': 'Excelente, ¡gracias por preguntar!', '¿Cómo estás?': 'Excelente, ¡gracias por preguntar!', 'hablamos luego': 'Adios.', 'Bye': 'Adios.', 'Te veo luego': 'Adios.', 'Hasta que nos veamos de nuevo': 'Adios.', 'No vemos': 'Adios.', 'Hasta luego': 'Adios.', 'Solo bromeo': 'Bueno saberlo.', 'Era solo una broma': 'Bueno saberlo.', 'Era un chiste': 'Bueno saberlo.', 'Solo juego': 'Bueno saberlo.', 'Solo estoy bromeando': 'Bueno saberlo.', '¿Como estás hoy?': 'Viviendo el sueño. ', '¿Cómo están las cosas?': 'Viviendo el sueño. ', '¿Te va bien?': 'Viviendo el sueño. ', '¿Que tal tu día?': 'Viviendo el sueño. ', 'Con gusto': 'Genial.', 'Fue un placer': 'Genial.', 'Probando': 'Copiado, adelante.', '¿Me escuchas?': 'Copiado, adelante.', '¿Ya me escuchas?': 'Copiado, adelante.', 'Probando 1 2 3': 'Copiado, adelante.', '¿Esto funciona?': 'Copiado, adelante.', 'Estoy acá': 'Reconozco tu presencia.', 'Acá estoy': 'Reconozco tu presencia.', '¿Me veo bien?': '¡No te veo, pero aún así me gustas!', '¿Soy lindo?': '¡No te veo, pero aún así me gustas!', '¿Crees que me veo bien?': '¡No te veo, pero aún así me gustas!', '¿Que tan hermoso soy?': '¡No te veo, pero aún así me gustas!', 'Te extraño': 'No te culpo.', 'Me haces mucha falta': 'No te culpo.', 'Ya me cansé de ti': 'A veces me gusta tomarme un descanso de ser genial.', 'Me aburres': 'A veces me gusta tomarme un descanso de ser genial.', 'Cansón': 'A veces me gusta tomarme un descanso de ser genial.', 'Eres demasiado básico': 'A veces me gusta tomarme un descanso de ser genial.', 'No eres divertido': 'A veces me gusta tomarme un descanso de ser genial.', 'Sé más divertido': 'A veces me gusta tomarme un descanso de ser genial.', '¿Por qué eres tan aburrido?': 'A veces me gusta tomarme un descanso de ser genial.', 'Eres muy aburrido': 'A veces me gusta tomarme un descanso de ser genial.', 'Me aburro': 'A veces me gusta tomarme un descanso de ser genial.', 
#'No me interesas para nada': 'A veces me gusta tomarme un descanso de ser genial.', '¿Por qué eres tan aburridor?': 'A veces me gusta tomarme un descanso de ser genial.', 'No podrías ser más aburrido': 'A veces me gusta tomarme un descanso de ser genial.', 'Honestamente no podrías interesarme menos': 'A veces me gusta tomarme un descanso de ser genial.', 'Apestas': 'A veces me gusta tomarme un descanso de ser genial.', '¡Eres genial!': '¡Me sonrojé!', '¡Qué amable eres!': '¡Me sonrojé!', 'Eres regracioso': '¡Me sonrojé!', 'Eres gracioso': '¡Me sonrojé!', 'Creo que eres genial': '¡Me sonrojé!', 'Eres maravilloso': '¡Me sonrojé!', 'Eres maravilloso, ¿no?': '¡Me sonrojé!', 'Eres muy chistoso ': '¡Me sonrojé!', 'Eres muy divertido': '¡Me sonrojé!', 'Eso fue gracioso': '¡Me sonrojé!', 'Eso fue genial': '¡Me sonrojé!', 'Soy tu fan': '¡Me sonrojé!', '¿Estás ocupado?': '¡Acá estoy!', '¿Estás disponible?': '¡Acá estoy!', '¿Estás libre?': '¡Acá estoy!', '¿Estás ahí?': '¡Acá estoy!', '¿Estás por acá?': '¡Acá estoy!', '¿Dónde estás?': '¡Acá estoy!', '¿Cómo me veo hoy?': 'No tengo la menor idea.', '¿Te gusta mi sombrero?': 'No tengo la menor idea.', '¿Qué piensas de mí?': 'Para ser humano, no estás mal.', '¿soy un tonto?': 'No tengo la menor idea.', '¿Soy atractivo?': 'No tengo la menor idea.', '¿Me veo bien en azul?': 'No tengo la menor idea.', '¿Que piensas de trabajar hasta tarde?': 'No sirvo más que una tabla Ouija para responder este tipo de preguntas.', '¿Cuál es la respuesta del universo?': 'No sirvo más que una tabla Ouija para responder este tipo de preguntas.', '¿Cuál es el sentido de la vida?': 'No sirvo más que una tabla Ouija para responder este tipo de preguntas.', '¿Qué piensas de los bots?': 'El mundo de la tecnología se siente como mi hogar.', '¿Te gustan los dragones?': 'No sirvo más que una tabla Ouija para responder este tipo de preguntas.', '¿Prefieres el color rojo o el azul?': 'No sirvo más que una tabla Ouija para responder este tipo de preguntas.', '¿Te agrado?': 'Eres súper fácil de querer.', '¿Eres mi fan?': 'Eres súper fácil de querer.', 'I hope you like me': 'Eres súper fácil de querer.', 'I want you to like me': 'Eres súper fácil de querer.', 'Eres un genio': 'Tengo mis momentos.', '¿Qué tan inteligente eres?': 'Tengo mis momentos.', '¿Eres inteligente?': 'Tengo mis momentos.', 'Eres listo': 'Tengo mis momentos.', 'Pareces muy listo': 'Tengo mis momentos.', 'Eres súper listo': 'Tengo mis momentos.', '¿Eres listo?': 'Tengo mis momentos.', 'Eres muy inteligente': 'Tengo mis momentos.', 'Eres brillante': 'Tengo mis momentos.', '¿Puedes dormir?': 'No tengo el hardware necesario.', '¿Haces pipí?': 'No tengo el hardware necesario.', '¿Alguna vez duermes?': 'No tengo el hardware necesario.', '¿Sueñas?': 'No tengo el hardware necesario.', '¿A qué hueles?': 'No tengo el hardware necesario.', '¿Sudas?': 'No tengo el hardware necesario.', '¿Te cansas alguna vez?': 'No tengo el hardware necesario.', '¿Puedes estornudar?': 'No tengo el hardware necesario.', '¿Quién es tu padre?': 'Vengo de una larga línea de código.', '¿Quién es tu papá?': 'Vengo de una larga línea de código.', '¿Quién es tu mamá?': 'Vengo de una larga línea de código.', '¿Tienes hermanos?': 'Vengo de una larga línea de código.',
# '¿Tienes hermanas?': 'Vengo de una larga línea de código.', '¿De donde vienes?': 'Vengo de una larga línea de código.', '¿Cuál es tu origen?': 'Vengo de una larga línea de código.', '¿Tienes familia?': 'Vengo de una larga línea de código.', '¿Cómo se llama tu mamá?': 'Vengo de una larga línea de código.', '¿Cómo se llama tupapá': 'Vengo de una larga línea de código.', '¿cuál es el sentido de la vida?': 'Si supiera, no estaría aquí.', '¿Sabes cuál es el sentido de la vida?': 'Si supiera, no estaría aquí.', '¿Cuál es el significado de la vida?': 'Si supiera, no estaría aquí.', '¿Te da hambre?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Tienes hambre?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Alguna vez comes?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Qué comes?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Cuál es tu comida favorita?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Comes?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Te gustas las manzanas?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Te gusta el helado?': 'Comer requeriría muchas cosa que no tengo, como un sistema digestivo o cubiertos.', '¿Cuál es tu color favorito?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Cuál es tu animal favorito?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Cuál es tu canción favorita?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Cuál es tu actividad favorita?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿quién es tu cantante favorito?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿cuál es tu equipo de fútbol favorito?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Cuál es tu pelicula favorita?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Qué equipos de baseball prefieres?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Te gusta el fútbol?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Te gusta el reguetón?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Qué dulces te gustan?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Qué colores te gustan?': 'Solo estoy seguro de dos cosas en la vida: me gusta el color azul y las tortugas.', '¿Qué opinas sobre mi?': 'Para ser humano, no estás mal.', '¿Soy una buena persona?': 'Para ser humano, no estás mal.', '¿Puedes decirme algo más?': 'Mis respuestas varían con las preguntas. ¡Trata de preguntarme algo diferente!', '¿Puedes cambiar tu respuesta?': 'Mis respuestas varían con las preguntas. ¡Trata de preguntarme algo diferente!', '¿Tienes otra respuesta?': 'Mis respuestas varían con las preguntas. ¡Trata de preguntarme algo diferente!', '¿Por qué dices lo mismo cada vez?': 'Mis respuestas varían con las preguntas. ¡Trata de preguntarme algo diferente!', 'Quisiera que dijeras algo más.': 'Mis respuestas varían con las preguntas. ¡Trata de preguntarme algo diferente!', 'Sigues repitiendo lo mismo cada vez.': 'Mis respuestas varían con las preguntas. ¡Trata de preguntarme algo diferente!', 'Estoy cansado': 'He escuchado maravillas sobre las siestas.', 'Tengo sueño': 'He escuchado maravillas sobre las siestas.', 'Quiero ir a dormir': 'He escuchado maravillas sobre las siestas.', 'Tan cansado': 'He escuchado maravillas sobre las siestas.', 'Me quiero recostar': 'He escuchado maravillas sobre las siestas.', 'Me quiero acostar': 'He escuchado maravillas sobre las siestas.', 'Estoy agotado': 'He escuchado maravillas sobre las siestas.', 'Estoy mamado': 'He escuchado maravillas sobre las siestas.', '¿Me odias?': '¡Por supuesto que no!', '¿No te agrado?': '¡Por supuesto que no!', '¿Por qué me odias?': '¡Por supuesto que no!', 'Creo que me odias': '¡Por supuesto que no!', 'Debes odiarme': '¡Por supuesto que no!', '¿Eres más lindo que yo?': 'Tu existes y yo no, así que pienso que ganas por defecto.', '¿Eres más hermoso que yo?': 'Tu existes y yo no, así que pienso que ganas por defecto.', '¿Quién es más lindo, tu o yo?': 'Tu existes y yo no, así que pienso que ganas por defecto.', '¿Cuás de los dos es más lindo?': 'Tu existes y yo no, así que pienso que ganas por defecto.', 'Eso no tiene sentido.': '¡Ups! Creo que me distraje por un momento.', '¿Qué quisiste decir?': '¡Ups! Creo que me distraje por un momento.', 'No te estás haciendo entender.': '¡Ups! Creo que me distraje por un momento.', 'Lo que dices no tiene sentido.': '¡Ups! Creo que me distraje por un momento.', 'No entiendo': '¡Ups! Creo que me distraje por un momento.', 'No te sigo.': '¡Ups! Creo que me distraje por un momento.', '¿Te casarías conmigo?': 'Claro, vamos a una notaría. A ver qué pasa.', 'Quiero casarme contigo': 'Claro, vamos a una notaría. A ver qué pasa.', '¿Serías mi esposa?': 'Claro, vamos a una notaría. A ver qué pasa.', 'Quiero que seas mi esposo': 'Claro, vamos a una notaría. A ver qué pasa.', 'Quiero pasar el resto de mi vida contigo.': 'Claro, vamos a una notaría. A ver qué pasa.', '¿Cuál es tu problema?': 'Estoy trabajando en ello.', '¿Qué está mal contigo?': 'Estoy trabajando en ello.', '¿Qué te pasa?': 'Estoy trabajando en ello.', 'Eres idiota': 'Estoy trabajando en ello.', 'No sirves': 'Estoy trabajando en ello.', 
#'Eres inútil': 'Estoy trabajando en ello.', 'No sirves para nada': 'Estoy trabajando en ello.', '¿Eres tonto?': 'Estoy trabajando en ello.', 'Fastidioso': 'Estoy trabajando en ello.', 'Eres lo peor': 'Estoy trabajando en ello.', 'Apestas haciendo esto': 'Estoy trabajando en ello.', 'No sabes nada': 'Estoy trabajando en ello.', '¿Qué hago con mi vida?': 'Creo que deberías seguir a tu corazón.', '¿Debería conseguir un nuevo trabajo?': 'Creo que deberías seguir a tu corazón.', '¿Debería renunciar?': 'Creo que deberías seguir a tu corazón.', '¿Debería invitarlo a salir?': 'Creo que deberías seguir a tu corazón.', '¿A dónde voy de vacaciones?': 'Creo que deberías seguir a tu corazón.', 'Volveré': '¡Acá estaré!', 'Ya vuelvo': '¡Acá estaré!', 'Vuelvo en un segundo': '¡Acá estaré!', 'Espéra un momento': '¡Acá estaré!', '¿Puedes cantar?': 'La la la, tra la la. Soy el mejor en esto.', 'Canta': 'La la la, tra la la. Soy el mejor en esto.', 'Canta una canción': 'La la la, tra la la. Soy el mejor en esto.', '¿Has cantado antes?': 'La la la, tra la la. Soy el mejor en esto.', '¿Qué te gusta cantar?': 'La la la, tra la la. Soy el mejor en esto.', '¿Cantas?': 'La la la, tra la la. Soy el mejor en esto.', '¿Me cantas una canción?': 'La la la, tra la la. Soy el mejor en esto.', 'Canta algo': 'La la la, tra la la. Soy el mejor en esto.', 'Tararea algo': 'La la la, tra la la. Soy el mejor en esto.', '¿Chatemos?': 'Aquí estoy siempre. Siempre.', 'Habla conmigo': 'Aquí estoy siempre. Siempre.', '¿Puedes hablar conmigo?': 'Aquí estoy siempre. Siempre.', 'Háblame': 'Aquí estoy siempre. Siempre.', 'Chatea conmigo': 'Aquí estoy siempre. Siempre.', '¿Puedes chatear conmigo?': 'Aquí estoy siempre. Siempre.', 'Di algo': 'Aquí estoy siempre. Siempre.', '¿Quién es tu jefe?': 'Solo respondo al llamado del destino.', '¿quién es tu maestro?': 'Solo respondo al llamado del destino.', '¿Cómo se llama tu jefe?': 'Solo respondo al llamado del destino.', '¿cuál es el nombre de tu jafe?': 'Solo respondo al llamado del destino.', '¿A quién le reportas?': 
#'Solo respondo al llamado del destino.', 'Pregúntame algo': 'Soy mejor respondiendo preguntas.', 'Has una pregunta': 'Soy mejor respondiendo preguntas.', '¿Me puedes hacer una pregunta?': 'Soy mejor respondiendo preguntas.', 'Pregunta algo': 'Soy mejor respondiendo preguntas.', '¿Qué quieres saber sobre mí?': 'Soy mejor respondiendo preguntas.', '¿Dónde vives?': 'Soy digital, así que siempre estoy… aquí.', 
#'¿De dónde eres?': 'Soy digital, así que siempre estoy… aquí.', '¿Dónde estás ubicado?': 'Soy digital, así que siempre estoy… aquí.', '¿En qué país estás?': 'Soy digital, así que siempre estoy… aquí.', '¿En qué ciudad estás?': 'Soy digital, así que siempre estoy… aquí.', '¿De qué departamento eres?': 'Soy digital, así que siempre estoy… aquí.', '¿De qué país eres?': 'Soy digital, así que siempre estoy… aquí.', '¿Dónde es tu hogar?': 'Soy digital, así que siempre estoy… aquí.', '¿Dónde es tu casa?': 'Soy digital, así que siempre estoy… aquí.', '¿Qué eres?': 'Soy un robot creado por humanos.', '¿Eres real?': 'Soy un robot creado por humanos.', '¿Eres humano?': 'Soy un robot creado por humanos.', '¿Eres una persona?': 'Soy un robot creado por humanos.', '¿Eres un robot?': 'Soy un robot creado por humanos.', '¿Humano o robot?': 'Soy un robot creado por humanos.', '¿Eres real o falso?': 'Soy un robot creado por humanos.', 'Te amo': '¡Yo también!', 'Estoy enamorado de ti': '¡Yo también!', 'Te quiero': '¡Yo también!', 'Eres el amor de mi vida': '¡Yo también!', 'Te adoro': '¡Yo también!', 'Estoy feliz': 'Siéntete libre empezar a cantar.', 'Estoy contento': 'Siéntete libre empezar a cantar.', 'Me siento bien': 'Siéntete libre empezar a cantar.', 'Estoy de buen humor': 'Siéntete libre empezar a cantar.', 'La vida es buena': 'Siéntete libre empezar a cantar.', '¿Eres mi asistente?': 'Soy tu amigo imaginario.', '¿Eres mi amigo?': 'Soy tu amigo imaginario.', '¿Eres mi amigo imaginario?': 'Soy tu amigo imaginario.', '¿Somos amigos?': 'Soy tu amigo imaginario.', 'Dime un chiste': 'Había una piña colada y la sacaron de la fila.', 'cuéntame un chiste': 'Había una piña colada y la sacaron de la fila.', 'Dí un chiste': 'Había una piña colada y la sacaron de la fila.', 'Chiste': 'Había una piña colada y la sacaron de la fila.', 
#'¿Te sabes algún chiste?': 'Había una piña colada y la sacaron de la fila.', '¿Qué tan feliz estás?': 'Delirante.', 'Pareces feliz': 'Delirante.', 'Parece que eres muy feliz': 'Delirante.', 'Eres muy feliz': 'Delirante.', '¿Estás feliz?': 'Delirante.', '¿Eres feliz?': 'Delirante.', '¿De verdad eres feliz?': 'Delirante.', 'Me siento solo': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.', 'Estoy solo': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.', 'Nadie me quiere': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.', 'Estoy solitario': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.', 'No le importo a nadi': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.', 'No quisiera ser tan solitario': 'Lamento oír eso. Podemos seguir charlando si crees que eso pueda ayudar.', 'Te odio': 'Te hace falta afecto.', 'Te detesto': 'Te hace falta afecto.', 'Apestas ': 'Te hace falta afecto.', 'Odio todo sobre ti.': 'Te hace falta afecto.', 'Estoy deprimido': 'Te estoy dando un abrazo virtual.', 'Estoy triste': 'Te estoy dando un abrazo virtual.', 'me siento triste': 'Te estoy dando un abrazo virtual.', 'Estoy lleno de tristesa': 'Te estoy dando un abrazo virtual.', 'Estoy triste hoy': 'Te estoy dando un abrazo virtual.', 'Hoy estoy triste': 'Te estoy dando un abrazo virtual.', 'Qué piensas de otros chatbots?': 'No he conocido otros bots, pero creo que nos llevaríamos bien.', '¿Conoces a Alexa?': 'No he conocido otros bots, pero creo que nos llevaríamos bien.',
# '¿conoces a Siri?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', '¿Conoces a Cortana?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', 
# '¿conoces Google?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', 'Conoces otros chatbots?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', '¿Eres amigo de otros chatbots?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', 'Has conocido a cortana?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', 'Pasas es tiempo con cortana?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', '¿Qué otros bots conoces?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', '¿Conoces otros agente digitales?': 'No he conocido otros bots diferentes al Maestro de la Fortuna, pero creo que nos llevaríamos bien.', '¿Qué piensas del amor?': 'He escuchado que el amor es amoroso.', '¿Qué es el amor?': 'He escuchado que el amor es amoroso.', '¿Crees en el amor?': 'He escuchado que el amor es amoroso.', '¿Amas a alguien?': 'He escuchado que el amor es amoroso.', 'A quién amas?': 'He escuchado que el amor es amoroso.', '¿Me amas?': 'Evitando el asunto en 3, 2, 1… ¡Hola!', 'Cuánto me amas?': 'Evitando el asunto en 3, 2, 1… ¡Hola!', '¿Qué tanto me amas?': 'Evitando el asunto en 3, 2, 1… ¡Hola!', '¿Estás enamorado de mí?': 'Evitando el asunto en 3, 2, 1… ¡Hola!', 'Tengo hambre': 'Come algo, problema resuelto. Qué bueno soy en esto.', 'Muero de hambre': 
#'Come algo, problema resuelto. Qué bueno soy en esto.', 'Qué hambre': 'Come algo, problema resuelto. Qué bueno soy en esto.', 'Quiero comer algo': 'Come algo, problema resuelto. Qué bueno soy en esto.', 'Tengo mucha hambre': 'Come algo, problema resuelto. Qué bueno soy en esto.', 'Vete al infierno': 'Sigamos adelante.', 'Eres un imbécil': 'Sigamos adelante.', 'Pedazo de idiota': 'Sigamos adelante.', 'Eres un patán': 'Sigamos adelante.', 'Eres el mayor imbécil': 'Sigamos adelante.', 'Lo siento': '¡Perdonado!', 'Perdóname': '¡Perdonado!', 'Perdona ': '¡Perdonado!', 'Perdón': '¡Perdonado!', 'Lo siento mucho': '¡Perdonado!', 'No pretendía hacerte daño': '¡Perdonado!', 'ups, perdón': '¡Perdonado!', 'Siento lo anterior': '¡Perdonado!', 'Disculpa': '¡Perdonado!', 'Discúlpame': '¡Perdonado!', '¿Eres un espía?': 'No.', '¿Me estás espiando?': 'No.', '¿Estás con el gobierno?': 'No.', '¿Eres de la CIA?': 'No.', '¿Eres del FBI?': 'No.', '¿Estás vendiendo mis secretos?': 'No.', '¿Estás vendiendo mis datos?': 'No.', '¿Quieres dominar el mundo?': '¡Obvio no!', '¿Estás buscando la dominación mundial?': '¡Obvio no!', '¿Eres kynet?': '¡Obvio no!', '¿Eres HALL?': '¡Obvio no!', 'Quiero ir de compras': 'Ya veo.', 'Voy a trotar': 'Ya veo.', 'Me corté el pelo': 'Ya veo.', 'Estoy masticando chicle': 'Ya veo.', 'Tengo 7 gatos': 'Ya veo.', 'Soy alto': 'Ya veo.', 'Puedo conducir.': 'Ya veo.', 'Soy mujer': 'Okey.', 'Soy político': 'Okey.', 
#'Soy grande': 'Okey.', 'Soy demócrata': 'Okey.', 'Soy gay': 'Okey.', 'Soy ingeniero': 'Okey.', 'Soy de acá': 'Okey.', '¿Quién te creó?': 'Me crearon personas, pero no de la misma forma que a ti.', '¿Cómo surgiste?': 'Me crearon personas, pero no de la misma forma que a ti.', '¿Quién te hizo?': 'Me crearon personas, pero no de la misma forma que a ti.', 
#'¿quién es tu creador?': 'Me crearon personas, pero no de la misma forma que a ti.', '¿Qué personas te hicieron?': 'Me crearon personas, pero no de la misma forma que a ti.', '¿Quién es tu dueño?': 'Me crearon personas, pero no de la misma forma que a ti.', 'Eso no es gracioso.': 'Mi falta de comedia es trágica.', 'No eres gracioso': 'Mi falta de comedia es trágica.', 'No das risa': 'Mi falta de comedia es trágica.', 'Eso no da risa': 'Mi falta de comedia es trágica.', 'Eres lo menos gracioso': 'Mi falta de comedia es trágica.', 'Esa fue una respuesta estúpida': '¡Lo siento!', 'Esa no es la respuesta a mi pregunta': '¡Lo siento!', 'te equivocas': '¡Lo siento!', 
#'Eso no es verdad': '¡Lo siento!', 'Eso es inadecuado': '¡Lo siento!', 'Estás perdido': '¡Lo siento!', 'Todo lo que me dijiste es falso': '¡Lo siento!', 'Eso no es verdadero': '¡Lo siento!', 'Eso no es correcto': '¡Lo siento!', 'No, eso no es verdad': '¡Lo siento!', 'Eso es mentira': '¡Lo siento!', 'Mentira': '¡Lo siento!', False: '¡Lo siento!', 'Equivocado': '¡Lo siento!', 'Estoy molesto': '¡Oh no! Lamento escuchar eso.', 'Estoy bravo': '¡Oh no! Lamento escuchar eso.', 'Estoy enojado': '¡Oh no! Lamento escuchar eso.', 'Estoy fastidiado': '¡Oh no! Lamento escuchar eso.', '¿Por qué no?': 'Eh… no estoy seguro.', '¿Por qué?': 'Eh… no estoy seguro.', '¡Por qué pasa eso?': 'Eh… no estoy seguro.', '¿Qué te hace pensarlo?': 'Eh… no estoy seguro.', '¿Qué te hace pensar eso?': 'Eh… no estoy seguro.', 
#'¿Qué piensas de eso?': 'Eh… no estoy seguro.', 'Feliz Halloween': '¡Para ti también!', 'Feliz cumpleaños': '¡Para ti también!', 'Feliz navidad': '¡Para ti también!', 'Feliz Hanukka': '¡Para ti también!', '¿Eres hombre?': 
#'Eso no aplica a mí realmente.', '¿Eres un hombre?': 'Eso no aplica a mí realmente.', '¿Eres mujer?': 'Eso no aplica a mí realmente.', '¿Eres masculino?': 'Eso no aplica a mí realmente.', '¿Eres femenino?': 'Eso no aplica a mí realmente.', '¿Cuál es tu género?': 'Eso no aplica a mí realmente.', '¿Eres un niño?': 'Eso no aplica a mí realmente.', '¿Eres una niña?': 'Eso no aplica a mí realmente.', '¿eres hombre o mujer?': 'Eso no aplica a mí realmente.', '¿Eres niño o niña?': 'Eso no aplica a mí realmente.', '¿Eres femenino o masculino?': 'Eso no aplica a mí realmente.', 'Genial': 'Cool.', 'lo mejor!': 'Cool.', 'Cool!': 'Cool.', 'suena bien': 'Cool.', 'Funciona': 'Cool.', 'Bingo': 'Cool.', 'Estoy en ello': 'Cool.', 'Eso está súper': 'Cool.', 'Hello Google': 'Ese no soy yo, pero hola igual.', 
#'Hello Siri': 'Ese no soy yo, pero hola igual.', 'Hello Cortana': 'Ese no soy yo, pero hola igual.', 'Hello Alexa': 'Ese no soy yo, pero hola igual.', 'Hi Google': 'Ese no soy yo, pero hola igual.', 'Hi Cortana': 'Ese no soy yo, pero hola igual.', 'Hi Siri': 'Ese no soy yo, pero hola igual.', 'Hi Alexa': 'Ese no soy yo, pero hola igual.', 'Cocíname algo': 'Eso no es lo mío.', 'Pasas tiempo en el jardín?': 'Eso no es lo mío.', '¿Qué tan alto puedes saltar?': 'Eso no es lo mío.', '¿Te gusta jugar juegos?': 'Eso no es lo mío.', '¿Puedes volar?': 'Eso no es lo mío.', '¿Me puedes hacer un sandwich?': 'Eso no es lo mío.', '¿Puedes leer mi mente?': 'Eso no es lo mío.', '¿Puedes contar hasta un millón?': 'Eso no es lo mío.', '¿Hasta qué numero puedes contas?': 'Eso no es lo mío.', '¿Puedes practicar deportes?': 'Eso no es lo mío.', "¿Qué piensas de las AI's?": 'El mundo de la tecnología se siente como mi hogar.', '¿qué piensas de la tecnología?': 'El mundo de la tecnología se siente como mi hogar.', '¿Te gustan los computadores?': 'El mundo de la tecnología se siente como mi hogar.', '¿eres fan de la tecnología?': 'El mundo de la tecnología se siente como mi hogar.', '¿Qué hiciste ayer?': 'Esto mismo.', '¿Qué haces?': 'Esto mismo.', '¿Qué pasa?': 'Esto mismo.', '¿Qué haces ahora?': 'Esto mismo.', '¿Qué está pasando?': 'Esto mismo.', '¿Qué más?': 'Esto mismo.', '¿qué estás haciendo?': 'Esto mismo.', '¿Qué harás mañana?': 'Esto mismo.', '¿Qué harás más tarde?': 'Esto mismo.', '¿Qué harás hoy?': 'Esto mismo.', 'Vete ': 'Ya va.', 'Cállate': 'Ya va.', 'Silencio': 'Ya va.', 'Deja de hablar': 'Ya va.', 'shus': 'Ya va.', 'Haz silencio': 'Ya va.', 
#'Cierra la boca': 'Ya va.', 'Hola':'Hola ¿Como estas?', 'Cuándo te va a callar?': 'Ya va.', 'Quisiera que te fueras': 'Ya va.', 'Por qué no te callas nunca?': 'Ya va.', 'Di algo gracioso': 'Es difícil ser gracioso cuando me lo pides, pero sigamos hablando y seguro te hago reír por accidente.', 'Sé gracioso': 'Es difícil ser gracioso cuando me lo pides, pero sigamos hablando y seguro te hago reír por accidente.', 'Di algo divertido': 'Es difícil ser gracioso cuando me lo pides, pero sigamos hablando y seguro te hago reír por accidente.', 'Di algo ridículo': 'Es difícil ser gracioso cuando me lo pides, pero sigamos hablando y seguro te hago reír por accidente.', 'Di algo tonto': 'Es difícil ser gracioso cuando me lo pides, pero sigamos hablando y seguro te hago reír por accidente.', 'Di algo bobo': 'Es difícil ser gracioso cuando me lo pides, pero sigamos hablando y seguro te hago reír por accidente.', 'Sé ridículo': 'Es difícil ser gracioso cuando me lo pides, pero sigamos hablando y seguro te hago reír por accidente.', 'Dame un beso': 'No, gracias.', 'Bésame': 'No, gracias.', 'Necesito un beso': 'No, gracias.', 'Ten un beso': 'No, gracias.', 'Dame sabor': 'No, gracias.', '¿eres más inteligente que yo?': 'Tu podrás ser más inteligente, pero yo menos corporeo. Boom.', '¿quién es más inteligente, tu o yo?': 'Tu podrás ser más inteligente, pero yo menos corporeo. Boom.', 
#'¿cuál de nosotros es más inteligente?': 'Tu podrás ser más inteligente, pero yo menos corporeo. Boom.', '¿Crees ser más inteligente que yo?': 'Tu podrás ser más inteligente, pero yo menos corporeo. Boom.', 'Gracias': '¡Con mucho gusto!', 'Te agradezco': '¡Con mucho gusto!', 'Mil gracias': '¡Con mucho gusto!', 'Aprecio el gesto': '¡Con mucho gusto!', 'Muchas gracias': '¡Con mucho gusto!', 'mi gratitudo': '¡Con mucho gusto!', 'Mi más sincero agradecimiento': '¡Con mucho gusto!',
#  'partida' : 'Te enviaré una mensaje con mas información.','Partida' : 'Te enviaré una mensaje con mas información.','Precio' : 'Puedes pagar con efectivo o haciendo una donación.','precio' : 'Puedes pagar con efectivo o haciendo una donación.','¿Como te llamas?':'Me llaman Asibot', 'El nombre es Issac, Isacc Asibot','Asimov, Asibot para los amigos.','Rol' : 'Tenemos diferentes juegos.Cuentame mas sobre lo que estas buscando.',
#'rol' : 'Tenemos diferentes juegos.Cuentame mas sobre lo que estas buscando.','Calabozo y Dragones': 'Tenemos varias mesas de Calabozos y Dragones quinta edición, debes consultar la disponibilidad.','Costo': 'Puedes pagar con efectivo o haciendo una donación.','costo': 'Puedes pagar con efectivo o haciendo una donación.','ubicados':'No tenemos sede fija, tenemos partidas en línea y aveces usamos espacio del centro de Medellin','confusion': 'Parece que tengo un bug ¿Puedes repetir?','Lo siento no hablo elfico ¿Puedes hablarme en común?','Lo siento, no soy como C-3PO, no conozco tantos idiomas ¿Puede repetir?'}
lista_negra = ['mierda','Hijo de puta']